app:
  title: Gitpod Demo
  baseUrl: http://localhost:3000

gitpod:
  baseUrl: 'https://gitpod.io/'

organization:
  name: Gitpod Demo

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007


  csp:
    connect-src: ["'self'", 'http:', 'https:']
 
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  database:
    client: better-sqlite3
    connection: ':memory:'

# integrations:
#   github:
#     - host: github.com
#       token: $GH_PW
#   gitlab:
#     - host: gitlab.com
#       token: $GL_PW

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, API, System, Domain, Resource, Location, User, Group]
  locations:
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
# auth:
#   environment: development
#   providers:
#     github:
#       development:
#         clientId: $GH_CLIENT
#         clientSecret: $GH_SECRET
