---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-kumquat
  links:
    - url: https://gitpod.io/workspaces
      title: Gitpod Dashboard
      icon: dashboard
spec:
  type: team
  children: []
  members: [lou, pauline]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lou
spec:
  type: member
  memberOf: [team-kumquat]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pauline
spec:
  type: member
  memberOf: [team-kumquat]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-grapefruits
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-playback
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-media
spec:
  type: team
  children: []
