apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-artist
  description: Artist main website
spec:
  type: website
  lifecycle: production
  owner: team-kumquat
  system: artist-engagement-portal
  consumesApis: ["component:artist-lookup"]
